import { PGlite } from '@electric-sql/pglite';
import { readFileSync, readdirSync } from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
const uid = n => `00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const admin=uid(1), patient=uid(2), other=uid(3), unverified=uid(4), p=uid(10), c=uid(20), cOther=uid(21), expired=uid(22), s=uid(30);
let checks=0;
const check=(actual,expected,label)=>{assert.deepEqual(actual,expected,label);checks++;console.log('PASS',label);};
await db.exec(`CREATE ROLE anon NOLOGIN; CREATE ROLE authenticated NOLOGIN; CREATE ROLE service_role NOLOGIN; CREATE SCHEMA auth;
CREATE TABLE auth.users(id uuid PRIMARY KEY, email text, email_confirmed_at timestamptz);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
GRANT USAGE ON SCHEMA public,auth TO anon,authenticated;
`);
for(const file of readdirSync('supabase/migrations').sort()) if(file.endsWith('.sql')) await db.exec(readFileSync(`supabase/migrations/${file}`,'utf8'));
await db.query(`INSERT INTO auth.users VALUES ($1,'admin@example.test',now()),($2,'patient@example.test',now()),($3,'other@example.test',now()),($4,'patient@example.test',null)`,[admin,patient,other,unverified]);
await db.query(`INSERT INTO public.user_roles(user_id,role) VALUES ($1,'admin'),($2,'user'),($3,'user'),($4,'user')`,[admin,patient,other,unverified]);
async function as(role,user,query,args=[]) {await db.exec(`SET ROLE ${role}`);await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[user]);try{return await db.query(query,args);}finally{await db.exec('RESET ROLE');}}
async function denied(role,user,query,args=[],code='42501'){let caught;try{await as(role,user,query,args);}catch(e){caught=e.code;}check(caught,code,`Bloqueado: ${role} ${query.split(' ')[0]}`);}
await as('authenticated',admin,'INSERT INTO public.patients(id,name,email) VALUES ($1,$2,$3)',[p,'Paciente Fictício','patient@example.test']);
await as('authenticated',admin,`INSERT INTO public.consultations(id,patient_id,patient_name,consultation_date,invite_email,invite_expires_at) VALUES ($1,$4,'Paciente Fictício','2026-09-12','patient@example.test',now()+interval '1 day'),($2,$4,'Outro Fictício','2026-09-12','other@example.test',now()+interval '1 day'),($3,$4,'Paciente Fictício','2026-09-12','patient@example.test',now()-interval '1 day')`,[c,cOther,expired,p]);
await as('authenticated',admin,`INSERT INTO public.consultation_drafts(consultation_id) VALUES ($1),($2)`,[c,cOther]);
for(const table of ['patients','consultations','anamnesis_submissions','consultation_drafts']) await denied('anon','',`SELECT * FROM public.${table}`);
check((await as('authenticated',patient,'SELECT id FROM public.consultations')).rows.map(r=>r.id),[c],'Paciente vê somente convite próprio e vigente');
check((await as('authenticated',unverified,'SELECT id FROM public.consultations')).rows,[],'E-mail não confirmado não recebe convite');
check((await as('authenticated',patient,'SELECT * FROM public.patients')).rows,[],'Paciente não acessa cadastro administrativo');
check((await as('authenticated',patient,'SELECT * FROM public.consultation_drafts')).rows,[],'Paciente não lê ficha clínica administrativa');
const insert='INSERT INTO public.anamnesis_submissions(id,consultation_id,answers,confirmed_name,accepted) VALUES ($1,$2,$3,$4,$5)';
await denied('authenticated',patient,insert,[s,cOther,{patientName:'Fictício'},'Paciente Teste',true]);
await denied('authenticated',patient,insert,[s,expired,{patientName:'Fictício'},'Paciente Teste',true]);
await denied('authenticated',unverified,insert,[s,c,{patientName:'Fictício'},'Paciente Teste',true]);
await denied('authenticated',patient,insert,[s,c,{patientName:'Fictício'},'Paciente Teste',false],'23514');
await denied('authenticated',patient,`INSERT INTO public.anamnesis_submissions(id,consultation_id,answers,confirmed_name,accepted,submitted_by) VALUES ($1,$2,'{}','Paciente Teste',true,$3)`,[s,c,other]);
await denied('authenticated',patient,`INSERT INTO public.anamnesis_submissions(id,consultation_id,answers,confirmed_name,accepted,confirmed_at) VALUES ($1,$2,'{}','Paciente Teste',true,now())`,[s,c]);
await as('authenticated',patient,insert,[s,c,{patientName:'Fictício'},'Paciente Teste',true]);
const saved=(await as('authenticated',patient,'SELECT * FROM public.anamnesis_submissions WHERE id=$1',[s])).rows[0];
check(saved.submitted_by,patient,'Autoria gerada pelo banco');
check(!!saved.confirmed_at,true,'Confirmação datada pelo banco');
check((await as('authenticated',other,'SELECT * FROM public.anamnesis_submissions')).rows,[],'Outro paciente não lê respostas');
check((await as('authenticated',admin,'SELECT id FROM public.anamnesis_submissions')).rows.length,1,'Admin lê respostas para revisar');
await denied('authenticated',patient,'UPDATE public.anamnesis_submissions SET answers=\'{}\' WHERE id=$1',[s]);
await denied('authenticated',admin,'DELETE FROM public.anamnesis_submissions WHERE id=$1',[s]);
check((await as('authenticated',patient,'UPDATE public.consultation_drafts SET version=1 RETURNING *')).rows,[],'Paciente não altera ficha clínica');
check((await as('authenticated',admin,'UPDATE public.consultation_drafts SET anamnesis_id=$1,version=1 WHERE consultation_id=$2 AND version=0 RETURNING version',[s,c])).rows,[{version:1}],'Admin vincula anamnese à própria consulta');
check((await as('authenticated',admin,'UPDATE public.consultation_drafts SET version=2 WHERE consultation_id=$1 AND version=0 RETURNING version',[c])).rows,[],'Versão antiga não sobrescreve uma atualização');
await denied('authenticated',admin,'UPDATE public.consultation_drafts SET anamnesis_id=$1 WHERE consultation_id=$2',[s,cOther],'23503');
await denied('authenticated',admin,'INSERT INTO public.reports(consultation_id,anamnesis_id) VALUES ($1,$2)',[cOther,s],'23503');
await as('authenticated',admin,'INSERT INTO public.reports(consultation_id,anamnesis_id) VALUES ($1,$2)',[c,s]);
check((await as('authenticated',patient,'SELECT * FROM public.reports')).rows,[],'Paciente não acessa histórico de relatórios');
const create='SELECT public.create_patient_consultation($1,$2,$3,$4,$5,$6) AS id';
const createArgs=[uid(40),uid(50),'Paciente Novo','novo@example.test','2026-09-12',false];
await denied('anon','',create,createArgs);
await denied('authenticated',patient,create,createArgs);
check((await as('authenticated',admin,create,createArgs)).rows,[{id:uid(40)}],'Admin cria paciente e consulta em uma transação');
check((await as('authenticated',admin,'SELECT version FROM public.consultation_drafts WHERE consultation_id=$1',[uid(40)])).rows,[{version:0}],'Criação inclui ficha inicial');
await as('authenticated',admin,create,createArgs);
check((await as('authenticated',admin,'SELECT id FROM public.consultations WHERE patient_id=$1',[uid(50)])).rows.length,1,'Repetição da criação não duplica consulta');
check((await as('authenticated',admin,create,[uid(41),uid(50),'Nome Ignorado','novo@example.test','2026-09-13',true])).rows,[{id:uid(41)}],'Nova consulta reutiliza o paciente existente');
check((await as('authenticated',admin,'SELECT patient_name FROM public.consultations WHERE id=$1',[uid(41)])).rows,[{patient_name:'Paciente Novo'}],'Nome da consulta vem do cadastro escolhido');
await denied('authenticated',admin,create,[uid(42),uid(51),'Paciente Revertido','rollback@example.test',null,false],'23502');
check((await as('authenticated',admin,'SELECT id FROM public.patients WHERE id=$1',[uid(51)])).rows,[],'Falha na consulta reverte também a criação do paciente');
await denied('authenticated',admin,create,[uid(40),uid(50),'Paciente Novo','novo@example.test','2026-09-15',false],'23505');
console.log(`${checks} verificações PostgreSQL aprovadas`);
await db.close();
