/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ClinicalFormRouteImport } from './routes/clinical-form'
import { Route as BodyCompositionRouteImport } from './routes/body-composition'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedJornadaIndexRouteImport } from './routes/_authenticated/jornada/index'
import { Route as AuthenticatedJornadaIdRouteImport } from './routes/_authenticated/jornada/$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalFormRoute = ClinicalFormRouteImport.update({
  id: '/clinical-form',
  path: '/clinical-form',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyCompositionRoute = BodyCompositionRouteImport.update({
  id: '/body-composition',
  path: '/body-composition',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedJornadaIndexRoute =
  AuthenticatedJornadaIndexRouteImport.update({
    id: '/jornada/',
    path: '/jornada/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJornadaIdRoute = AuthenticatedJornadaIdRouteImport.update({
  id: '/jornada/$id',
  path: '/jornada/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/body-composition': typeof BodyCompositionRoute
  '/clinical-form': typeof ClinicalFormRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/review': typeof ReviewRoute
  '/success': typeof SuccessRoute
  '/upload': typeof UploadRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/jornada/$id': typeof AuthenticatedJornadaIdRoute
  '/jornada/': typeof AuthenticatedJornadaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/body-composition': typeof BodyCompositionRoute
  '/clinical-form': typeof ClinicalFormRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/review': typeof ReviewRoute
  '/success': typeof SuccessRoute
  '/upload': typeof UploadRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/jornada/$id': typeof AuthenticatedJornadaIdRoute
  '/jornada': typeof AuthenticatedJornadaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/body-composition': typeof BodyCompositionRoute
  '/clinical-form': typeof ClinicalFormRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/review': typeof ReviewRoute
  '/success': typeof SuccessRoute
  '/upload': typeof UploadRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/jornada/$id': typeof AuthenticatedJornadaIdRoute
  '/_authenticated/jornada/': typeof AuthenticatedJornadaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/body-composition'
    | '/clinical-form'
    | '/history'
    | '/mcp'
    | '/review'
    | '/success'
    | '/upload'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/jornada/$id'
    | '/jornada/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/body-composition'
    | '/clinical-form'
    | '/history'
    | '/mcp'
    | '/review'
    | '/success'
    | '/upload'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/jornada/$id'
    | '/jornada'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/body-composition'
    | '/clinical-form'
    | '/history'
    | '/mcp'
    | '/review'
    | '/success'
    | '/upload'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/_authenticated/jornada/$id'
    | '/_authenticated/jornada/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BodyCompositionRoute: typeof BodyCompositionRoute
  ClinicalFormRoute: typeof ClinicalFormRoute
  HistoryRoute: typeof HistoryRoute
  McpRoute: typeof McpRoute
  ReviewRoute: typeof ReviewRoute
  SuccessRoute: typeof SuccessRoute
  UploadRoute: typeof UploadRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical-form': {
      id: '/clinical-form'
      path: '/clinical-form'
      fullPath: '/clinical-form'
      preLoaderRoute: typeof ClinicalFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body-composition': {
      id: '/body-composition'
      path: '/body-composition'
      fullPath: '/body-composition'
      preLoaderRoute: typeof BodyCompositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jornada/': {
      id: '/_authenticated/jornada/'
      path: '/jornada'
      fullPath: '/jornada/'
      preLoaderRoute: typeof AuthenticatedJornadaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jornada/$id': {
      id: '/_authenticated/jornada/$id'
      path: '/jornada/$id'
      fullPath: '/jornada/$id'
      preLoaderRoute: typeof AuthenticatedJornadaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedJornadaIdRoute: typeof AuthenticatedJornadaIdRoute
  AuthenticatedJornadaIndexRoute: typeof AuthenticatedJornadaIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedJornadaIdRoute: AuthenticatedJornadaIdRoute,
  AuthenticatedJornadaIndexRoute: AuthenticatedJornadaIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BodyCompositionRoute: BodyCompositionRoute,
  ClinicalFormRoute: ClinicalFormRoute,
  HistoryRoute: HistoryRoute,
  McpRoute: McpRoute,
  ReviewRoute: ReviewRoute,
  SuccessRoute: SuccessRoute,
  UploadRoute: UploadRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
