BEGIN;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE oid = 'public.reports'::regclass AND relrowsecurity)
    OR has_table_privilege('anon', 'public.reports', 'SELECT,INSERT,UPDATE,DELETE')
    OR EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'reports' AND ('public' = ANY(roles) OR 'anon' = ANY(roles)))
    OR (SELECT count(*) FROM pg_policies WHERE schemaname = 'public' AND tablename = 'reports' AND roles = ARRAY['authenticated']::name[] AND policyname IN ('Administrators can view reports', 'Administrators can insert reports', 'Administrators can update reports', 'Administrators can delete reports')) <> 4 THEN
    RAISE EXCEPTION 'Aplique primeiro as migrações de acesso administrativo já presentes no projeto (20260911131740 e 20260911132739).';
  END IF;
END $$;


CREATE TABLE public.patients (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL CHECK (char_length(btrim(name)) BETWEEN 2 AND 150),
  email text NOT NULL DEFAULT '' CHECK (char_length(email) <= 254),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.consultations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL REFERENCES public.patients(id),
  patient_name text NOT NULL CHECK (char_length(btrim(patient_name)) BETWEEN 2 AND 150),
  consultation_date date NOT NULL,
  invite_email text NOT NULL DEFAULT '' CHECK (invite_email = lower(btrim(invite_email)) AND char_length(invite_email) <= 254),
  invite_expires_at timestamptz NOT NULL DEFAULT now() + interval '14 days',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX consultations_patient_idx ON public.consultations(patient_id, consultation_date DESC);

-- Narrow identity check: only the current user's verified email is returned.
-- No clinical data is read and no service-role client is used.
CREATE FUNCTION public.current_verified_email() RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
  SELECT lower(u.email) FROM auth.users u
  WHERE u.id = (SELECT auth.uid()) AND u.email_confirmed_at IS NOT NULL;
$$;
REVOKE ALL ON FUNCTION public.current_verified_email() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.current_verified_email() TO authenticated;

CREATE TABLE public.anamnesis_submissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL REFERENCES public.consultations(id),
  answers jsonb NOT NULL CHECK (jsonb_typeof(answers) = 'object' AND octet_length(answers::text) <= 100000),
  confirmed_name text NOT NULL CHECK (char_length(btrim(confirmed_name)) BETWEEN 3 AND 150),
  accepted boolean NOT NULL CHECK (accepted),
  declaration_version text NOT NULL DEFAULT '2026-09-11',
  confirmed_at timestamptz NOT NULL DEFAULT now(),
  submitted_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  UNIQUE (id, consultation_id)
);
CREATE INDEX anamnesis_consultation_idx ON public.anamnesis_submissions(consultation_id, confirmed_at DESC);
CREATE TABLE public.consultation_drafts (
  consultation_id uuid PRIMARY KEY REFERENCES public.consultations(id),
  body_composition jsonb CHECK (body_composition IS NULL OR jsonb_typeof(body_composition) = 'object'),
  clinical_data jsonb CHECK (clinical_data IS NULL OR jsonb_typeof(clinical_data) = 'object'),
  anamnesis_id uuid,
  version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
  FOREIGN KEY (anamnesis_id, consultation_id) REFERENCES public.anamnesis_submissions(id, consultation_id)
);

ALTER TABLE public.reports ADD COLUMN consultation_id uuid REFERENCES public.consultations(id);
ALTER TABLE public.reports ADD COLUMN anamnesis_id uuid;
ALTER TABLE public.reports ADD CONSTRAINT reports_anamnesis_consultation_fk
  FOREIGN KEY (anamnesis_id, consultation_id) REFERENCES public.anamnesis_submissions(id, consultation_id);
ALTER TABLE public.reports ADD CONSTRAINT reports_anamnesis_needs_consultation CHECK (anamnesis_id IS NULL OR consultation_id IS NOT NULL);
CREATE INDEX reports_consultation_idx ON public.reports(consultation_id);

ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consultations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.anamnesis_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consultation_drafts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.patients, public.consultations, public.anamnesis_submissions, public.consultation_drafts FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON public.patients, public.consultations TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.consultation_drafts TO authenticated;
GRANT SELECT ON public.anamnesis_submissions TO authenticated;
-- Attribution, timestamp and declaration version are generated by the database.
GRANT INSERT (id, consultation_id, answers, confirmed_name, accepted) ON public.anamnesis_submissions TO authenticated;

CREATE POLICY patients_admin ON public.patients FOR ALL TO authenticated
  USING (public.has_role((SELECT auth.uid()), 'admin')) WITH CHECK (public.has_role((SELECT auth.uid()), 'admin'));
CREATE POLICY consultations_admin ON public.consultations FOR ALL TO authenticated
  USING (public.has_role((SELECT auth.uid()), 'admin')) WITH CHECK (public.has_role((SELECT auth.uid()), 'admin'));
CREATE POLICY consultations_invited_patient ON public.consultations FOR SELECT TO authenticated
  USING (invite_email <> '' AND invite_email = (SELECT public.current_verified_email()) AND invite_expires_at > now());
CREATE POLICY drafts_admin ON public.consultation_drafts FOR ALL TO authenticated
  USING (public.has_role((SELECT auth.uid()), 'admin')) WITH CHECK (public.has_role((SELECT auth.uid()), 'admin'));
CREATE POLICY anamnesis_admin_read ON public.anamnesis_submissions FOR SELECT TO authenticated
  USING (public.has_role((SELECT auth.uid()), 'admin'));
CREATE POLICY anamnesis_patient_read ON public.anamnesis_submissions FOR SELECT TO authenticated
  USING (submitted_by = (SELECT auth.uid()) AND EXISTS (
    SELECT 1 FROM public.consultations c WHERE c.id = consultation_id AND c.invite_email <> ''
      AND c.invite_email = (SELECT public.current_verified_email()) AND c.invite_expires_at > now()
  ));
CREATE POLICY anamnesis_submit ON public.anamnesis_submissions FOR INSERT TO authenticated
  WITH CHECK (submitted_by = (SELECT auth.uid()) AND (public.has_role((SELECT auth.uid()), 'admin') OR EXISTS (
    SELECT 1 FROM public.consultations c WHERE c.id = consultation_id AND c.invite_email <> ''
      AND c.invite_email = (SELECT public.current_verified_email()) AND c.invite_expires_at > now()
  )));
-- No UPDATE/DELETE grants or policies for confirmed responses.

-- One transaction creates the patient, consultation and draft. Retries use the
-- same IDs. SECURITY INVOKER retains the authenticated user's grants and RLS.
CREATE FUNCTION public.create_patient_consultation(
  _id uuid, _patient_id uuid, _name text, _email text,
  _date date, _existing_patient boolean
) RETURNS uuid LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$
DECLARE
  patient public.patients%ROWTYPE;
  consultation public.consultations%ROWTYPE;
  normalized_email text := lower(btrim(_email));
BEGIN
  IF NOT public.has_role((SELECT auth.uid()), 'admin') THEN
    RAISE EXCEPTION 'Acesso restrito a administradores.' USING ERRCODE = '42501';
  END IF;
  IF NOT _existing_patient THEN
    INSERT INTO public.patients(id, name, email)
      VALUES (_patient_id, btrim(_name), normalized_email) ON CONFLICT (id) DO NOTHING;
  END IF;
  SELECT * INTO patient FROM public.patients WHERE id = _patient_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Paciente indisponível.' USING ERRCODE = '23503';
  END IF;
  IF NOT _existing_patient AND (patient.name <> btrim(_name) OR patient.email <> normalized_email) THEN
    RAISE EXCEPTION 'O cadastro foi alterado. Reabra a consulta.' USING ERRCODE = '23505';
  END IF;
  INSERT INTO public.consultations(id, patient_id, patient_name, consultation_date, invite_email)
    VALUES (_id, _patient_id, patient.name, _date, normalized_email) ON CONFLICT (id) DO NOTHING;
  SELECT * INTO consultation FROM public.consultations WHERE id = _id;
  IF consultation.patient_id <> _patient_id OR consultation.consultation_date <> _date
    OR consultation.invite_email <> normalized_email THEN
    RAISE EXCEPTION 'A consulta já foi criada com outros dados.' USING ERRCODE = '23505';
  END IF;
  INSERT INTO public.consultation_drafts(consultation_id) VALUES (_id)
    ON CONFLICT (consultation_id) DO NOTHING;
  RETURN _id;
END;
$$;
REVOKE ALL ON FUNCTION public.create_patient_consultation(uuid, uuid, text, text, date, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_patient_consultation(uuid, uuid, text, text, date, boolean) TO authenticated;
COMMIT;
